### ISSUE TITLE
Linux 4.4: 100mbit network does not work

### ISSUE THREAD

**Issue by ndz215** [edelweiss-tech/linux-kernel#1]
1000Мb network works Ok, but 100Mb network hangs on dhclient eth0 request:

root@baikal:/home/user# dhclient eth0
[  621.837314]  No MAC Management Counters available
[  621.843963] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready

[  625.803959] baikal-dwmac 1f05e000.eth1 eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[  625.814637] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready

^C

Checked two cases:
1. Old 10/100Mb router
2. 1000Mb link, but with downgraded configuration:
ethtool -s eth0 autoneg off
ethtool -s eth0 speed 100

**Comment by vvv19xx** [comment]
The problem was due to CONFIG_BAIKAL_ERRATA_GMAC=y in baikal_mitx_defconfig.
Fixed.
